services:
  db:
    image: postgres:16-alpine
    container_name: nogagames-db
    environment:
      POSTGRES_USER: nogagames
      POSTGRES_PASSWORD: nogagames
      POSTGRES_DB: nogagames
    ports:
      - "5432:5432"
    volumes:
      - nogagames-pgdata:/var/lib/postgresql/data

volumes:
  nogagames-pgdata: